[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "HIIdentify"
authors = [{name = "Bethan Easeman", email = "be329@bath.ac.uk"}]
dynamic = ["version", "description"]
